### PR TITLE
Fix import in stl/mesh.py

### LINKED ISSUE #215: AttributeError: module 'stl' has no attribute 'BaseStl
Adarsh2425 ➜ /workspaces/Slicer-for-multi-toolhead-application (main) $ /home/codespace/.python/current/bin/python3 /workspaces/Slicer-for-multi-toolhead-application/imex_slicer.py
Traceback (most recent call last):
  File "/workspaces/Slicer-for-multi-toolhead-application/imex_slicer.py", line 15, in <module>
    from stl import mesh
  File "/home/codespace/.python/current/lib/python3.10/site-packages/stl/mesh.py", line 4, in <module>
    class mesh(stl.BaseStl):
AttributeError: module 'stl' has no attribute 'BaseStl

i dont know what to do now

### PR DESCRIPTION
**Pull request by carolinafernandezp**
Fixes #215

### CODE REVIEW

**Comment by wolph** [comment]
In what case would this fix anything?

The linked issue is most likely due to conflicting packages instead

**Comment by carolinafernandezp** [comment]
> In what case would this fix anything?
> 
> The linked issue is most likely due to conflicting packages instead

I was having the same problem as the person that raised the issue (and had no other stl module installed and no other file named `stl.py` in my directory) and this resolved it.

**Comment by wolph** [comment]
Very odd... it shouldn't make any difference.

Can you please test what happens if you add this at the top of `mesh.py`?
```from . import stl
print(stl)
```

**Comment by carolinafernandezp** [comment]
> Very odd... it shouldn't make any difference.
> 
> Can you please test what happens if you add this at the top of `mesh.py`?
> 
> ```python
> from . import stl
> print(stl)
> ```

I get the following:
`<module 'stl.stl' from '/home/lab/.local/lib/python3.10/site-packages/stl/stl.py'>`

**Comment by wolph** [comment]
Why did you close the PR? Was the issue solved some other way?

**Pull request closed without merging**
