### PR TITLE
Fix for issue #52

### PR DESCRIPTION
**Pull request by hroncok**
See https://github.com/WoLpH/numpy-stl/issues/52

TODO:

* [x] Make the PyQt5 test dependency optional
* [x] Fix the issue with uselocale() from Cython code
* [x] Check macOS
* [x] Check cura

### CODE REVIEW

**Comment by WoLpH** [comment]
For ease we could make the `PyQt5` optional and simply add a separate tox+travis environment for that. It will still get automatic tests but it saves everyone from installing PyQt5 which can be a pain if there are no binaries available for your platform.

**Comment by hroncok** [comment]
I've added it to Python 3.6 nix environment and will focus on the fix.
Later we can do it differently.

**Comment by hroncok** [comment]
I have a fix that works on my Linux. Not sure if it should be non-Windows or Linux only (aka I have no idea if it works / is required on MacOS or FreeBSD). It is also most likely glibc only and never tested on MUSL.

**Comment by hroncok** [comment]
Also, I haven't tested this im cura yet.

**Comment by hroncok** [comment]
Fixes the cura issue.

**Comment by hroncok** [comment]
OK, it didn't compile on macOS, so I've used `IF Linux`.

I'm basically done now. Please let me know if I shell approach this differently.

**Comment by WoLpH** [comment]
The fix looks great to me so I'm very happy with it. If osx users report the issue I can always fix it myself. You've done the hard work already.

Once again thank you so much for all of the effort! I'd never have found it myself.

**Pull request merged**
