### PR TITLE
Fix ASCII/binary detection issues

### LINKED ISSUE #156: ASCII/binary detection issues
I just came across some STL files generated by the computational fluid dynamics software Star-CCM+, where numpy-stl fail to load the ASCII STL's.

This old bug in OpenFOAM have two simple examples attached:
https://bugs.openfoam.org/view.php?id=516
see the file "cubes.zip". I attach the same file here as a reference:
[cubes.zip](https://github.com/WoLpH/numpy-stl/files/5816483/cubes.zip)

The ASCII STL's start with " solid", i.e. a whitespace before the word "solid". This puzzles the automatic ASCII/binary detection in numpy-stl and it is attempted to read the file as binary, which fails.

The best descriptions I have found for the STL file format(s) are Wikipedia [1] and a page on fabbers.com [2]. Neither of them are perfectly clear on the validity of this file(s) coming from Star-CCM+... These resources (Wikipedia, Fabbers) are also sometimes in conflict, Wikipedia list tabs as examples of allowed whitespace characters and Fabbers explicitly write that this is not allowed. Fabbers, being an old resource, write that all coordinates must be non-negative, which is rarely enforced today. Wikipedia write that the file must start with the line "solid name", but later they state that whitespace may be used anywhere in the file except within numbers or words...

I then in the end conclude that whitespace are also allowed before the first "solid", and that both of the STL's in the attached file are valid STL's (even though both are really stupid in their own ways).

First I would like to know your thoughts on the validity of the attached STL's.

Then, secondly I do not like the current method of reading ASCII/binary STL's. I can force the reading of a binary STL with mode=Mode.BINARY, but the same is not true for Mode.ASCII, since by code design in stl.py:70 it nevertheless will jump to binary reading, since the first five characters of the file is not "solid"...

What would be the opinions on really having three modes: ASCII, binary and automatic? In ASCII mode it would never fall back to binary, in binary mode it would never fall back to ASCII and in automatic it would make an educated guess on the mode based on the file structure, and possibly fall back to the other mode if the first is failing. Opinions?

It can be possible for me to provide some pull request solving some of this, but I would like to hear your opinion first.

[1] https://en.wikipedia.org/wiki/STL_(file_format)
[2] http://www.fabbers.com/tech/STL_Format

### PR DESCRIPTION
**Pull request by hakostra**
This is an attempt to fix #156

 - STL files starting with a whitespace (first line indented) are now properly recognized as ASCII
 - If the file mode is ASCII go straight to ASCII reader, and if file mode is binary, go straight to binary reader
 - In automatic mode, if the file/stream start with word 'solid', possibly prepended by whitespace, try ASCII mode first and fallback to binary
 - If header contain non-ASCII characters, assume binary by default in automatic mode

I added three STL's in the tests-folder, but did not figure out how to include these in the testing framework, sorry. All of the STL's should read and parse.

The Cube.stl is a square cube from (x, y, z) = (0, 0, 0) to (2, 2, 2) in ASCII and binary format. The Cube.stl in ASCII format does not parse correctly with the current develop-branch, and this PR fixes this issue.

The CubeInvalidUnicode.stl is the same cube, but where a non-ASCII/non-Unicode character (0xFFFF) is inserted in the end of the 80-byte header. Reading in this file should cover the `except UnicodeError` part that is not covered by the existing tests.

In the end I want to mention that I was not completely satisfied with the changes I came up with in stl.py, because the `load`-function became less understandable. However, I think that if a file is opened in Mode.BINARY, it should go straight to the binary reader without checking particularly much about the header and trying ASCII first, and the same for Mode.ASCII. The automatic mode is complicated by needing to support autodetection in non-seekable streams, so this part is maybe best left as-is.

I am also slightly unsure about Python 2.7 support in this PR. I no longer have this available on my development machine and cannot test. I do however think that `header.decode("ascii").lstrip().lower()` is valid Python 2.7...

Thanks.

### CODE REVIEW

**Comment by hakostra** [comment]
I just realized the following: A perfectly valid binary STL can have a header with 80 bytes of NULL (0x00). I think this decodes to an empty string in Python. Also, there can be cases where the binary header contain less than 5 ASCII characters (e.g. the word 'STL') and then the rest null-bytes.

In these cases the check 
```
headerstr = header.decode("ascii").lstrip().lower()
possibly_ascii = True if headerstr[:5] == 'solid' else False
```
is slightly ugly ([:5] on a str with length < 5). Maybe a better syntax would have been
```
possibly_ascii = headerstr.startswith('solid')
```
However, i just checked, and it appears that
```
a = ""
test = a[:5]
```
is valid and raises no errors...

I do not have my development PC now, but I will construct such an STL tomorrow and check if it passes through in automatic mode.

**Comment by WoLpH** [comment]
> In these cases the check
> 
> ```
> headerstr = header.decode("ascii").lstrip().lower()
> possibly_ascii = True if headerstr[:5] == 'solid' else False
> ```
> 
> is slightly ugly ([:5] on a str with length < 5). Maybe a better syntax would have been
> 
> ```
> possibly_ascii = headerstr.startswith('solid')
> ```
> 
> However, i just checked, and it appears that
> 
> ```
> a = ""
> test = a[:5]
> ```
> 
> is valid and raises no errors...

It's not the prettiest, I'm trying to remember the reason for this syntax but both wil work.
Actually, it could have been reduced to:

```python
possibly_ascii = header.decode("ascii").lstrip().lower()[:5] = 'solid'
```

The True/False thing is silly because a `==` should always return a boolean

**Comment by hakostra** [comment]
You mean to use == don't you:
```
possibly_ascii = header.decode("ascii").lstrip().lower()[:5] == 'solid'
```
The reason for using [:5] originally might be because that was the only way to do this with a binary sequence, as it was previously.
For this PR I had to convert the header to a string, because otherwise I cannot do "lstrip" on it.

I also created an STL variant with a header consisting only of null-bytes, and it passes the automatic ASCII/binary detection without any problems. The 80-byte sequence of null's decode as I anticipated to an empty string.

**Comment by WoLpH** [comment]
> You mean to use == don't you:

Indeed, that was a typo :)

> The reason for using [:5] originally might be because that was the only way to do this with a binary sequence, as it was previously.
> For this PR I had to convert the header to a string, because otherwise I cannot do "lstrip" on it.

Ah... that explains a lot. It shouldn't be needed for bytes though:
```
In [1]: x = b' some binary string with spaces '

In [2]: x.strip()
Out[2]: b'some binary string with spaces'

In [3]: x.lstrip()
Out[3]: b'some binary string with spaces '
```

I think the slicing method was done mostly due to Python 2/3 incompatibility issues. But that's no longer relevant so it can be replaced :)

> I also created an STL variant with a header consisting only of null-bytes, and it passes the automatic ASCII/binary detection without any problems. The 80-byte sequence of null's decode as I anticipated to an empty string.

Nice :)

**Comment by hakostra** [comment]
Ah. So you can lstrip on bytes objects as well... I thought that was valid for 'str' only. Sorry, still get confused on this.

Anyhow, I think the ASCII decode is sensible, because if it contain binary content that cannot be decoded to ASCII in the header, it is at least not an ASCII STL file (but maybe someone tries an "unicode STL"?).

Also, let me know if you want me to do more on this PR.

**Comment by WoLpH** [comment]
I've made a few small changes but everything is merged beyond that :)

Thank you for the help!

**Pull request merged**
