### PR TITLE
Rename check to is_closed

### PR DESCRIPTION
**Pull request by NicholasWon47**

### CODE REVIEW

**Comment by WoLpH** [comment]
For the sake of backwards compatibility the check method needs to stay. But it could simply wrap the `is_closed` method. The idea is that multiple checks could be added over time, not just checking for closed geometries

**Comment by NicholasWon47** [comment]
I understood. In that cases, the method needs some docs :)

**Comment by NicholasWon47** [comment]
I simply wrapped 'is_closed' method. so you can use them in check method as a check routines.

**Comment by WoLpH** [comment]
Looks great. Thank you :)

**Pull request merged**
