### PR TITLE
Ensure py2 compatibility

### PR DESCRIPTION
**Pull request by loicgasser**
Fix issue described in https://github.com/WoLpH/numpy-stl/issues/10

_load_binary is correct this one fixes _write_binary

### CODE REVIEW

**Comment by WoLpH** [comment]
Awesome, thanks :)

Not sure why this wasn't caught by the unit tests though... it should have been. Do you have any example code we can add to the tests so this won't happen in the future?

**Comment by WoLpH** [comment]
Also, I've just pushed a fix for the travis code quality checks so you can ignore that :)

**Comment by loicgasser** [comment]
Yes fake8 complains.  There was an update this week and all my project now have the same error. 
So I can rebase on develop and the build should work ?
Also, yes we should try to test it, make sure it is for py2.

**Comment by loicgasser** [comment]
I rebased

Running ``py.test tests/test_convert.py`` locally without this fix does it does break the tests.

This is specific to older versions of python. (2.7.3 in my case)
The one you get with tox and travis is 2.7.9.

Since version 2.7.7 struct supports unicode.
See: https://hg.python.org/cpython/raw-file/v2.7.9/Misc/NEWS

- Issue #19099: The struct module now supports Unicode format strings.

This is the reason why it didn't show up in the tests.
Not sure if you want to test older versions/minor versions with tox though.

**Comment by WoLpH** [comment]
Odd, so the test fails locally but works on Travis. Thanks for the help regardless :)

**Pull request merged**
