### PR TITLE
Support empty lines in ASCII stl files

### PR DESCRIPTION
**Pull request by ncloward**
The spec is vague on how to handle empty lines in an STL file.  Some say
its allowed others don't say anything.  Its best to support it and be
more flexible.

### CODE REVIEW

**Comment by WoLpH** [comment]
Great pull request, the STL standard is indeed a bit vague but I don't see why this shouldn't be accepted.

**Comment by ncloward** [comment]
Thanks for the merge!  Is there anyway to get a release for this out?

**Comment by WoLpH** [comment]
Sorry about that, I've been quite busy lately. I've just deployed a new version :)

**Comment by ncloward** [comment]
I understand ;)  Thanks for the update!

**Pull request merged**
